List all tiers in membership stats / updates
swindonmakers/AccessSystem pull request #51
Opened 2023-03-03 11:04 UTC by castaway

2023-03-09 09:27 UTC, theorbtwo requested changes
See individual comments.  Re worrying about what income is being spent on if it's shown, I agree that it probably will, but that just means that we should do a better job explaining what our expenses are.

2023-03-09 22:29 UTC, castaway commented on lib/AccessSystem/Schema/ResultSet/Person.pm
> +    $now = DateTime->now()->subtract(years => 3);
Corrrect, fixed

2023-03-09 22:29 UTC, castaway commented on lib/AccessSystem/Schema/ResultSet/Person.pm
> +# my ($query, @bind) = $sqla->select({
2nd one, moved to NOTES

2023-03-10 18:46 UTC, theorbtwo approved these changes

2023-03-11 13:18 UTC, merged